framework:
  workflows:
    door_job:
      type: state_machine
      supports:
        - ZukunftsforumRissen\CommunityOffersBundle\Workflow\DoorJob
      marking_store:
        type: method
        property: status
      initial_marking: pending
      places:
        - pending
        - dispatched
        - executed
        - failed
        - expired
      transitions:
        dispatch:
          from: pending
          to: dispatched
        execute:
          from: dispatched
          to: executed
        fail:
          from: dispatched
          to: failed
        expire_pending:
          from: pending
          to: expired
        expire_dispatched:
          from: dispatched
          to: expired
