community_offers_controllers:
    resource: "../src/Controller/"
    type: attribute

co_app:
    path: /app
    controller: ZukunftsforumRissen\CommunityOffersBundle\Controller\Frontend\AppController
    methods: [GET]

co_demo:
    path: /demo
    controller: ZukunftsforumRissen\CommunityOffersBundle\Controller\Demo\DemoController
    methods: [GET]

co_device_monitor:
    path: /%contao.backend.route_prefix%/device-monitor
    controller: ZukunftsforumRissen\CommunityOffersBundle\Controller\Frontend\DeviceMonitorController
    methods: [GET]
    defaults:
        _scope: backend

co_door_workflow_inspector:
    path: /%contao.backend.route_prefix%/door-workflow
    controller: ZukunftsforumRissen\CommunityOffersBundle\Controller\Backend\DoorWorkflowInspectorController
    methods: [GET]
    defaults:
        _scope: backend
