services:
  ZukunftsforumRissen\CommunityOffersBundle\Door\DoorGatewayInterface:
    alias: ZukunftsforumRissen\CommunityOffersBundle\Door\MockDoorGateway

  test.ZukunftsforumRissen\CommunityOffersBundle\Service\DoorJobService:
    alias: ZukunftsforumRissen\CommunityOffersBundle\Service\DoorJobService
    public: true

  test.ZukunftsforumRissen\CommunityOffersBundle\Service\DoorWorkflowTimelineService:
    alias: ZukunftsforumRissen\CommunityOffersBundle\Service\DoorWorkflowTimelineService
    public: true

  test.ZukunftsforumRissen\CommunityOffersBundle\Service\DoorWorkflowDiagramService:
    alias: ZukunftsforumRissen\CommunityOffersBundle\Service\DoorWorkflowDiagramService
    public: true