name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    name: CI (PHP 8.4)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHPv4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2
          coverage: none

      - name: Composer validate
        run: composer validate --no-interaction --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --no-scripts

      - name: ECS (coding style)
        run: vendor/bin/ecs check

      - name: PHPStan (src)
        run: APP_ENV=test vendor/bin/phpstan analyse -c phpstan.neon

      - name: PHPStan (tests) (non-blocking)
        continue-on-error: true
        run: APP_ENV=test vendor/bin/phpstan analyse -c phpstan-tests.neon

      - name: PHPUnit
        run: APP_ENV=test vendor/bin/phpunit